name: ParkBan APK Builder

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build APK
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleDebug

      - name: Find APK
        run: find . -name "*.apk" -type f

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ParkBan
          path: "**/*.apk"
          if-no-files-found: error
